services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080" # nếu backend lắng nghe trên cổng 5000
    volumes:
      - ./EcoGreen/Extensions:/app/Extensions
    depends_on:
      - ollama
    networks:
      - ai_net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434" # Chỉ cần nếu bạn muốn test bằng curl ngoài host
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai_net
    restart: always
    command: >
      sh -c "ollama run tinyllama && ollama serve"

volumes:
  ollama_data:

networks:
  ai_net:
    driver: bridge
